### ISSUE TITLE
Question of Fig2(b)

### ISSUE THREAD

**Issue by hotfinda** [IDEA-Research/HumanTOMATO#11]
Hi, I am reading the original paper, but I notice that in Fig2(b) the text-motion alignment is finished during inference since it is marked with dotted line, why is that ?

**Comment by LinghaoChan** [comment]
@hotfinda Thanks for your attention. 

The dotted line is used for denoting inference only in the system overview figure. Here, the T-M alignment is only used during training. We think the TMR we trained will be public soon. If you have more questions, you can read the appendix or discuss them with us. 

Best,

Ling-Hao

**Comment by LinghaoChan** [comment]
Hi, @hotfinda! Has your question been resolved? If so, I will close the issue.
