### ISSUE TITLE
im exciting wait for your open

### ISSUE THREAD

**Issue by try2020-code** [IDEA-Research/HumanTOMATO#13]
so, waht time is it,  when will you open the code

**Comment by LinghaoChan** [comment]
Please stay tuned. we plan to release the text-motion alignment part codes in 1-2 weeks. You can try the demo [here](https://swanhub.co/demo/Evan/OpenTMR) first.

**Comment by LinghaoChan** [comment]
Hi @try2020-code !

We release the TMR training in the `./OpenTMA`. Please check it! 

[Note]: As the research target in this project is to clarify how to use text-motion alignment, TMR in our project is charged as TMA in the ICML-24 version.
