### ISSUE TITLE
VRAM  Need

### ISSUE THREAD

**Issue by yumianhuli2** [IDEA-Research/HumanTOMATO#14]
How much VRAM do I need to run the pre-trained model after release?Thank you！

**Comment by LinghaoChan** [comment]
> How much VRAM do I need to run the pre-trained model after release?Thank you！

Hi! Thanks for your interest on our project. In our practice, our model can be run in one NVIDIA A100 GPU with 80 GB. I remember it can also be run on one 4090 GPU. For detailed VRAM, we will test it and tell it to you! We may release the TMR part this week. You can try this part first. 

Best,

Ling-Hao Chen

**Comment by yumianhuli2** [comment]
> > How much VRAM do I need to run the pre-trained model after release?Thank you！
> 
> Hi! Thanks for your interest on our project. In our practice, our model can be run in one NVIDIA A100 GPU with 80 GB. I remember it can also be run on one 4090 GPU. For detailed VRAM, we will test it and tell it to you! We may release the TMR part this week. You can try this part first.
> 
> Best,
> 
> Ling-Hao Chen

thank u
