### ISSUE TITLE
Estimated code release date

### ISSUE THREAD

**Issue by ZikangLeng** [IDEA-Research/HumanTOMATO#2]
Thanks for the awesome work! Do you have a estimated release date for when the code and models(including mld, t2m-gpt) will be released?

**Comment by LinghaoChan** [comment]
Hi @ZikangLeng 

Thanks for your interest🌹. We are working hard on releasing the codes. Up to now, I am not sure when the whole project code will be public precisely. We have made the usage of data yesterday. We now plan to release the remaining codes step by step. We may release the training and the usage of TMR at first. And then, we will release the H2VQ. Please be patient. We will do these ASAP🏃.

🍷Cheers,
