### ISSUE TITLE
How to generate embeddings on the full datasets?

### ISSUE THREAD

**Issue by HonglinChu** [IDEA-Research/HumanTOMATO#22]
Hi, I test the demo code https://github.com/LinghaoChan/OpenTMA-demo. 
![image](https://github.com/IDEA-Research/HumanTOMATO/assets/11087575/049bc410-a4f6-4b8a-b39c-859b2b1ce2fd)
I am referring the code to know how to generate them more conveniently. Maybe you can provide the corresponding scripts.
https://github.com/IDEA-Research/HumanTOMATO/blob/7120079a6edae10482e934aad2d6050229a02796/OpenTMA/tma/models/modeltype/temos.py#L408

**Comment by LinghaoChan** [comment]
The core codes for saving `npy`s is here. 
https://github.com/IDEA-Research/HumanTOMATO/blob/7120079a6edae10482e934aad2d6050229a02796/OpenTMA/tma/models/modeltype/temos.py#L884

There are two ways for you to self-define the split. 

1. Revise the test split file during training. 
2. Run the test file of the OpenTMA. (point out the checkpoint name in the yaml file in advance.)
