### ISSUE TITLE
Any details of preparing Yang-style Tai Chi for training data?

### ISSUE THREAD

**Issue by hdjsjyl** [IDEA-Research/HumanTOMATO#5]
Hi Author,
    Thanks for sharing very excellent work. Would you share the details of converting Yang-style Tai Chi for training data? Thanks

**Comment by LinghaoChan** [comment]
Hi @hdjsjyl, thanks for your interest. 

You can refer to the `kungfu` subset of the [Motion-X](https://motion-x-dataset.github.io/) dataset.

**Comment by hdjsjyl** [comment]
Hi @LinghaoChan , really appreicate your help. Thanks

**Comment by hdjsjyl** [comment]
Hi @LinghaoChan ,
    Would you share the general steps for getting kungfu training data from videos or some data sources? I would like to learn how to get our own data through video basically. Thank you

**Comment by LinghaoChan** [comment]
Please refer to the motion-x paper. [link](https://arxiv.org/pdf/2307.00818.pdf)
