### ISSUE TITLE
Looking forward to the open source of the code.

### ISSUE THREAD

**Issue by liujf69** [IDEA-Research/HumanTOMATO#6]
Thank you for your great work. I'm looking forward to the open source of your code.

**Comment by LinghaoChan** [comment]
@liujf69 Thanks for your interest! We are working on this. We will first open-source the text-motion alignment part soon.

**Comment by LinghaoChan** [comment]
Hi @liujf69 !

We release the TMR training in the `./OpenTMA`. Please check it! 

[Note]: As the research target in this project is to clarify how to use text-motion alignment, TMR in our project is charged as TMA in the ICML-24 version.
