### ISSUE TITLE
When will you open the code？

### ISSUE THREAD

**Issue by feifeitu1** [IDEA-Research/HumanTOMATO#9]
Good idea!When will the code be released approximately?I really need your code as a reference.Thank you!

**Comment by LinghaoChan** [comment]
@feifeitu1 Thanks for your interest! We are working on this. We will first open-source the text-motion alignment part soon.

**Comment by LinghaoChan** [comment]
Hi @feifeitu1 !

We release the TMR training in the `./OpenTMA`. Please check it! 

[Note]: As the research target in this project is to clarify how to use text-motion alignment, TMR in our project is charged as TMA in the ICML-24 version.

**Comment by feifeitu1** [comment]
Oh,Thank you for your reply, I will read your codes later.
